name: Owl OS build

on: [push, pull_request, workflow_dispatch]

jobs:
  toolchain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make toolchain
  build:
    needs: toolchain
    runs-on: ubuntu-latest
    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: actions/checkout@v3
      - run: make clean
      - run: make all
