name: Owl OS build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update
      - run: sudo apt-get install libgmp3-dev
      - run: sudo apt-get install libmpfr-dev
      - run: sudo apt-get install mpc
      - uses: actions/checkout@v3
      - uses: ilammy/setup-nasm@v1
      - run: make toolchain
      - run: make clean
      - run: make all
